import os
import sys

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)

from backend.services.engine.qlib_app.schemas.backtest import QlibBacktestRequest
from backend.services.engine.qlib_app.services.strategy_builder import (
    CustomStrategyBuilder,
)

# Read temporary strategy generated by ide
with open(os.path.join(ROOT_DIR, "data/ai_ide/temp/temp_策略_2026_2_6.py")) as f:
    content = f.read()

builder = CustomStrategyBuilder()
try:
    from types import SimpleNamespace

    request = SimpleNamespace(
        strategy_content=content, strategy_params=SimpleNamespace()
    )
    res = builder._build_strategy_from_content(content, request=request)
    print(type(res))
    print(res)
except Exception:
    import traceback

    traceback.print_exc()
