# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path
from PyInstaller.utils.hooks import collect_all, collect_submodules

tool_root = Path(SPECPATH)
icon_path = tool_root / "icon.ico"

pyside6_datas, pyside6_bins, pyside6_hidden = collect_all("PySide6")

datas = [
    (str(tool_root / "README.md"), "."),
    (str(tool_root / "help.md"), "."),
    (str(tool_root / "requirements.txt"), "."),
    (str(tool_root / "version.json"), "."),
    (str(tool_root / "theme.qss"), "."),
    (str(tool_root / "_callback.py"), "."),
    (str(tool_root / "agent.py"), "."),
    (str(tool_root / "auth.py"), "."),
    (str(tool_root / "client.py"), "."),
    (str(tool_root / "config.py"), "."),
    (str(tool_root / "reporter.py"), "."),
    (str(tool_root / "triage.py"), "."),
    (str(tool_root / "updater.py"), "."),
] + pyside6_datas

hiddenimports = [
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "uuid",
    *collect_submodules("requests"),
    *collect_submodules("websocket"),
] + pyside6_hidden

a = Analysis(
    [str(tool_root / "desktop_app.py")],
    pathex=[str(tool_root)],
    binaries=pyside6_bins,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
excludes=[
        "tkinter",
        "pystray",
        "PIL",
        "PyQt5",
        "PyQt6",
        "PySide2",
        "torch",
        "torchvision",
        "torchaudio",
        "tensorflow",
        "numpy",
        "pandas",
        "scipy",
        "matplotlib",
        "IPython",
        "jupyter",
        "pytest",
        "black",
        "sphinx",
        "docutils",
        "nbformat",
        "nbconvert",
        "sympy",
        "h5py",
        "tables",
        "pyarrow",
        "numba",
        "llvmlite",
        "zmq",
        "jedi",
        "parso",
        "astroid",
        "pylint",
        "cryptography",
        "bcrypt",
        "sqlalchemy",
        "psycopg2",
        "MySQLdb",
        "pysqlite2",
        "grpc",
        "opentelemetry",
        "rich",
        "pygments",
        "lark",
        "regex",
        "dateutil",
        "pytz",
        "tzdata",
        "fsspec",
        "win32com",
        "pythoncom",
        "pywintypes",
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    exclude_binaries=False,
    name="QuantMindQMTAgent",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(icon_path) if icon_path.exists() else None,
    onefile=True,
    runtime_tmpdir=None,
)
